#!/bin/bash

# Add verbose directory change command. Should fix to check if colors are ok with >20 files. 
maxfiles=64
files_to_show=4
function c() {
  cd $@
  filecount=`ls -l | wc -l`
  if [ $filecount -gt $maxfiles ]; then
    ls -F --color=always | head -n "$files_to_show"
    echo "<$((filecount - $files_to_show)) more files>"
  else
    ls -CF --color=auto
  fi
}
export -f c
