#!/bin/bash

# List files to help orient for a new directory.
maxfiles=64
files_to_show=4
function _list_files() {
  filecount=`ls -l | wc -l`
  if [ $filecount -gt $maxfiles ]; then
    ls -F --color=always | head -n "$files_to_show"
    echo "<$((filecount - $files_to_show)) more files>"
  else
    ls -CF --color=auto
  fi
}

# Directory change with history
function c() {
  if [ $# -eq 0 ]; then
    pushd ~ > /dev/null
  else
    pushd "$@" > /dev/null
  fi
  _list_files
}

# Reverse last directory change
function b() {
  popd "$@" > /dev/null
  pwd
  _list_files
}

export -f c
export -f b
