#!/bin/bash
# ANSI color codes
RS="\[\033[0m\]"    # reset
HC="\[\033[1m\]"    # hicolor
UL="\[\033[4m\]"    # underline
INV="\[\033[7m\]"   # inverse background and foreground
BLK="\[\033[30m\]" # foreground black
RED="\[\033[31m\]" # foreground red
GRN="\[\033[32m\]" # foreground green
YEL="\[\033[33m\]" # foreground yellow
BLU="\[\033[34m\]" # foreground blue
MAG="\[\033[35m\]" # foreground magenta
CYN="\[\033[36m\]" # foreground cyan
WHT="\[\033[37m\]" # foreground white

BBLK="\[\033[90m\]" # foreground black
BRED="\[\033[91m\]" # foreground red
BGRN="\[\033[92m\]" # foreground green
BYEL="\[\033[93m\]" # foreground yellow
BBLU="\[\033[94m\]" # foreground blue
BMAG="\[\033[95m\]" # foreground magenta
BCYN="\[\033[96m\]" # foreground cyan
BWHT="\[\033[97m\]" # foreground white

BGBLK="\[\033[40m\]" # background black
BGRED="\[\033[41m\]" # background red
BGGRN="\[\033[42m\]" # background green
BGYEL="\[\033[43m\]" # background yellow
BGBLU="\[\033[44m\]" # background blue
BGMAG="\[\033[45m\]" # background magenta
BGCYN="\[\033[46m\]" # background cyan
BGWHT="\[\033[47m\]" # background white

#PS1="\D{%m/%d} \t \[\e[46m\]\u@\h\[\e[0;34m\] \W \[\e[0m\]" 
PS1="\D{%b %d}|\t $BCYN\u@\h$RS $BBLU\W$RS "
